// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\features\places\presentation\history\screens.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'place_search_screen.dart';