// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\core\domain.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'interfaces/interfaces.dart';
