// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\features\places\domain\entities.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'map_point_entity.dart';
