// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\core\data\http.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'dio_client.dart';