// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\uikit\themes\text.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'app_text_style.dart';
export 'app_text_theme.dart';