// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\features\places\presentation\list\screens.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'places_list_screen.dart';
export 'place_details_screen.dart';