// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\features\favorites\presentation\screens.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'favorites_screen.dart';