// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\core.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'constants/constants.dart';
export 'data/data.dart';
export 'domain/domain.dart';
