// c:\Users\Anechka\Desktop\projects\flutter_application_4\lib\core\domain\interfaces.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'i_database_client.dart';
export 'i_http_client.dart';
export 'i_search_history_client.dart';
